### ISSUE TITLE
bilibili跳转到视频指定时间点的url参数好像换了 

### ISSUE THREAD

**Issue by BlackStarStar** [sixiwanzi-live/zmdb#1]
现在应该是https://www.bilibili.com/video/BV1Ua411W7tg?t=3600&vd_source=481704e8b03eec140384b8f661522bd6

**Comment by sixiwanzi-live** [comment]
我看看，多谢提醒

**Comment by sixiwanzi-live** [comment]
已上线，版本号2.5.4~~~
